### ISSUE TITLE
smu as a library

### ISSUE THREAD

**Issue by B4rb3rouss** [Gottox/smu#12]
Reading smu.h, it seems that smu was, at some point, usable as a library.

That would be nice to use smu code in other project thanks to a "libsmu". Do you consider making it available as a library in the future?

**Comment by Gottox** [comment]
I prefer to keep it a standalone binary. Just use `popen()` to interact with it from other programs.

**Comment by B4rb3rouss** [comment]
I already use `popen` and wanted to use smu code directly instead so I don't have to `pledge("proc exec")`. But that's okay ::)

Thank you for the amazing smu.
